### PR TITLE
ObjectIdentifier can be used, if the protocol conforms to AnyObject

### PR DESCRIPTION
**Pull request by royalicing**
I think this should work. It makes sense that Notifiers must be class instances as they are used by reference.

### CODE REVIEW

**Comment by Inferis** [comment]
I didn't know of `ObjectIdentifier`. Nice.

But:

> /// In Swift, only class instances and metatypes have unique identities. There
> /// is no notion of identity for structs, enums, functions, or tuples.

I also noticed the AnyObject protocol is a @objc protocol, which is still not a "Pure Swift" implementation (although not sure that was your intention).

Additionally, not sure if this is the approach you want? We're now forcing to use absolute object references and cannot have to objects handle equality themselves...

**Comment by royalicing** [comment]
AnyObject is a core part of Swift. It may have things to make it more compatible with Objective-C, but as far as I know is considered pure Swift.

I think having a notification listener be a value type doesn’t really make sense. If it was, the value would have to include references to other objects in the graph – making changes on itself is pointless as nothing else references it. Value types as far as I know are best used for information and state, that sort of thing (which in Swift they are fantastic at).

**Comment by royalicing** [comment]
Also if a notifier (should it be called an observer?) was a value type, then when you add it to the `notifiers` array in `addNotifier()` you are making a copy of it.

**Comment by Inferis** [comment]
Ah yes, good point. :)

**Pull request closed without merging**
